apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-custodyandpossession-api
spec:
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    name: vv-custodyandpossession-api
  minReplicas: 3
  maxReplicas: 15
  targetCPUUtilizationPercentage: 80