apiVersion: v1
kind: Service
metadata:
  name: possession
  labels:
    name: possession
spec:
  ports:
    - name: api
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: vv-custodyandpossession-api
  sessionAffinity: None
  type: ClusterIP
